### ISSUE TITLE
[Feature Request] Support alternative fiat currencies

### ISSUE THREAD

**Issue by Technifocal** [pxsocs/thewarden#15]
As a British user, everything being tracked in USD isn't much help to me.

Maybe I'm missing something, but I can only see USD support in this app. Adding support for GBP/EUR/YPN/etc... should assist in international use.

**Comment by pxsocs** [comment]
In the works. Hopefully will be released under v0.03 which will have an option under user settings to select base currency which could be fiat (USD, JPY, EUR, etc) or BTC.

**Comment by pxsocs** [comment]
This is now available as a [pre-release on branch nonusd.](https://github.com/pxsocs/thewarden/tree/nonusd). 
```bash
git pull origin nonusd
```
to download and test this version.
This branch will merge into the master branch when a couple other features are finished (ETA next few weeks).
