### ISSUE TITLE
Followed Installation Instructions and got Server Error on Browser

### ISSUE THREAD

**Issue by PuraVlda** [pxsocs/thewarden#18]
Currently Running Samourai Dojo and wanted to run the Warden also, in connection to my Dojo.  Initial install I just followed the installation guide at:  https://github.com/pxsocs/thewarden/blob/master/INSTALL.MD

Currently running this on Mac High Sierra v. 10.13.6 

The guide was written well, got everything installed fine.  After Step 8, starting the application everything looked fine.  When I went to http://127.0.0.1:5000/ I got the following message. 
<img width="712" alt="Screen Shot 2019-08-10 at 1 43 54 PM" src="https://user-images.githubusercontent.com/51298667/62825172-73cea100-bb75-11e9-9361-85e9fbd4367c.png">

After doing this, I did not want to mess around with anything else, waiting for a solution.  My actual solution I want is to run pointed to my Dojo, that current setup is:

Dojo running with Docker on Mac, pointing at bitcoind on my node.

**Comment by pxsocs** [comment]
This issue appears to be in relation to issue #17. 
The next release should have a workaround solution to enable users to customize IP addresses.

**Comment by pxsocs** [comment]
Issue #17 is now closed. Flask actually has an argument to change the host ip. Just run:

```bash
python run.py --host 0.0.0.0
```
This will now make it accessible on your ip address (of the machine running the WARden). For example, if your IP is 192.168.1.2, you can navigate to:
```bash
http://192.168.1.2:5000
```
To get your ip address:
```bash
ìfconfig
```

Also, on the local machine you can use `http://localhost:5000/`
