### ISSUE TITLE
After Dockerizing, not able to host on a certain ip:port

### ISSUE THREAD

**Issue by calvinleungyk** [pxsocs/thewarden#21]
Tried putting thewarden into a Docker container but I wasn't able to access localhost:5000.  Running thewarden locally on a macbook pro and on an AWS EC2 machine works and I was able to access thewarden console from outside if `host='0.0.0.0'` is provided as an argument to `app.run()`.  I tried a sample flask app within a docker container and I was able to access it externally on both local macbook and AWS EC2.

Here is the Dockerfile contents:
```
FROM python:3.6

LABEL version='1.0'

EXPOSE 5000

RUN apt-get update && \
    apt-get install -y python3 python3-pip build-essential git && \
    pip3 install --upgrade pip==19.2.3

COPY . /app/thewarden
WORKDIR /app/thewarden

# RUN git clone https://github.com/pxsocs/thewarden.git
# RUN pip3 install virtualenv
# RUN virtualenv cb_env
# RUN . cb_env/bin/activate
RUN pip3 install -r requirements.txt

CMD ["python3", "-u", "warden.py", "--host", "0.0.0.0"]
```

What would be the issue preventing thewarden from being dockerized and hosted/ exposed to the host ip?

**Comment by pxsocs** [comment]
I have limited experience with Docker but will do some research on this

**Comment by calvinleungyk** [comment]
Yep - you got it right.  Must've dug too deep and overlooked this option.  Now going to `127.0.0.1:5000,` is working.  

However, `python warden.py --host [host_ip]` is not working for me.  Had to manually change `app.run(debug=flask_debug, threaded=True)` to `app.run(debug=flask_debug, threaded=True, host=[host_ip])` for it to work.

Thanks for the suggestion!

**Comment by calvinleungyk** [comment]
Updates: with `docker run`, you need to use the **container IP**; with `docker-compose up`, you need to use `0.0.0.0`.

**Comment by pxsocs** [comment]
In response to the `None` prints: 

That was a debugging print that should have been removed. It was placed to identify when the user was not logged in (current_user.id variable).

It's actually removed at the [development branch](https://github.com/pxsocs/thewarden/tree/development). Feel free to git pull from the development branch but keep in mind that there are several open items being worked on that branch. It does have a new look and feel and new analytics but, for now, it's also slower and a bit unstable.

Also, happy to help in understanding the app. Let me know if you have any other questions.

Finally, as for the initial issue, I'm closing it for now. Thanks for the feedback and for documenting the proper steps for a solution.

**Comment by calvinleungyk** [comment]
The prints still show up even though I'm logged in and it seems like current_user is None rather than the id is None:
```
thewarden_1  | Regenerating NAV. Please wait...
thewarden_1  | Regenerating NAV. Please wait...
thewarden_1  | Regenerating NAV. Please wait...
thewarden_1  | Regenerating NAV. Please wait...
thewarden_1  | Regenerating NAV. Please wait...
thewarden_1  | Exception in thread Thread-64:
thewarden_1  | Traceback (most recent call last):
thewarden_1  |   File "/app/thewarden/users/decorators.py", line 141, in func
thewarden_1  |     v = self.cache[key]
thewarden_1  | KeyError: (('chris', True), ())
thewarden_1  |
thewarden_1  | During handling of the above exception, another exception occurred:
thewarden_1  |
thewarden_1  | Traceback (most recent call last):
thewarden_1  |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
thewarden_1  |     self.run()
thewarden_1  |   File "/usr/local/lib/python3.6/threading.py", line 864, in run
thewarden_1  |     self._target(*self._args, **self._kwargs)
thewarden_1  |   File "/app/thewarden/users/decorators.py", line 152, in func
thewarden_1  |     v = self.cache[key] = f(*args, **kwargs), time.time()
thewarden_1  |   File "/app/thewarden/users/decorators.py", line 68, in timed
thewarden_1  |     return (method(*args, **kw))
thewarden_1  |   File "/app/thewarden/users/utils.py", line 522, in generatenav
thewarden_1  |     usernamehash = hashlib.sha256(current_user.username.encode(
thewarden_1  |   File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 348, in __getattr__
thewarden_1  |     return getattr(self._get_current_object(), name)
thewarden_1  | AttributeError: 'NoneType' object has no attribute 'username'
```
