### ISSUE TITLE
[Feature Request] Add support to importing xpubs through own personal node

### ISSUE THREAD

**Issue by pxsocs** [pxsocs/thewarden#3]
Create a connection to user's Bitcoin node to privately download transaction data from a list of xpubs.

**Comment by pxsocs** [comment]
This is actually a bit harder than I initially expected. Exploring a couple of options here but **looking for advice and feedback**:

1) [Electrum Personal Server](https://github.com/chris-belcher/electrum-personal-server) running on node : setup you xpub as a watch only wallet

2) Samourai [DOJO](https://samouraiwallet.com/dojo) - need to learn more if this is an option

**Comment by Technifocal** [comment]
FWIW Samourai Dojo should be an option. I am not affiliated to them, but my understanding is you'd:

POST `/xpub?xpub=yourxpubhere&type=restore&segwit=bip49orbip84orblank`

This would trigger a rescan of the blockchain for the xpub (one time, new blocks are automatically scanned). Once done, you can:

GET `/xpub/yourxpubhere`

would return the `balance`. If you want the individual transactions, query:

GET `/txs?active=yourxpubhere&count=numberoftxshere&page=pagecountfromzero`

It'd return all the transactions in a JSON array, including `block_height`, `inputs` and `outputs`. See more [here](https://github.com/Samourai-Wallet/samourai-dojo/blob/master/doc/GET_txs.md)

Full documentation available [here](https://github.com/Samourai-Wallet/samourai-dojo/blob/master/doc/README.md)

**Comment by pxsocs** [comment]
Right on. Exactly what I'm exploring. Right now synching a new node using the Dojo to run some tests and implement.

**Comment by pxsocs** [comment]
This is now implemented on version 0.1
